language: node_js
node_js:
  - 10.8.0
install:
  - npm install -g firebase-tools
script:
  - echo "Deploy"
  - cd sample
  - npm i
  - npm run generate
  - cd ..
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
