language: node_js
node_js:
  - 10.8.0
install:
  - npm install -g firebase-tools
after_success:
  - npm i -g firebase-ci
  - firebase-ci deploy
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
